// Package document manages trip documents (tickets, reservations, passports...). MongoDB holds the
// metadata and the storage port holds the file; clients upload and download directly against the
// storage through short-lived signed URLs, so the API never proxies file bytes.
package document

import (
	"context"
	"errors"
	"net/url"
	"regexp"
	"strings"
	"time"

	"rinotravel-api/internal/kernel"
	"rinotravel-api/internal/platform/ids"
	"rinotravel-api/internal/user"
)

type Type string

const (
	TypeTicket       Type = "TICKET"
	TypeReservation  Type = "RESERVATION"
	TypeBoardingPass Type = "BOARDING_PASS"
	TypeHotel        Type = "HOTEL"
	TypeInsurance    Type = "INSURANCE"
	TypeReceipt      Type = "RECEIPT"
	TypePassport     Type = "PASSPORT"
	TypeOther        Type = "OTHER"
)

func ParseType(s string) (Type, error) {
	switch t := Type(s); t {
	case TypeTicket, TypeReservation, TypeBoardingPass, TypeHotel, TypeInsurance, TypeReceipt, TypePassport, TypeOther:
		return t, nil
	}
	return "", errors.New("must be one of TICKET, RESERVATION, BOARDING_PASS, HOTEL, INSURANCE, RECEIPT, PASSPORT, OTHER")
}

type Visibility string

const (
	// VisibilityTrip lets every member of the trip read the document.
	VisibilityTrip Visibility = "TRIP"
	// VisibilityPrivate lets only the uploader read it, not even the trip owner.
	VisibilityPrivate Visibility = "PRIVATE"
)

func ParseVisibility(s string) (Visibility, error) {
	switch v := Visibility(s); v {
	case VisibilityTrip, VisibilityPrivate:
		return v, nil
	}
	return "", errors.New("must be TRIP or PRIVATE")
}

type Status string

const (
	// StatusPending means the metadata exists but the file has not been confirmed in storage.
	StatusPending Status = "PENDING"
	StatusReady   Status = "READY"
)

const MaxSize int64 = 25 << 20

var allowedMime = map[string]bool{
	"application/pdf": true, "image/jpeg": true, "image/png": true,
	"image/webp": true, "image/heic": true, "image/heif": true,
}

var checksumPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)

var linkTypes = map[string]bool{
	"trip": true, "itinerary_item": true, "flight": true, "hotel": true,
	"restaurant": true, "place": true, "transfer": true,
}

type Document struct {
	kernel.Base
	OwnerID  user.ID
	Name     string
	Type     Type
	FileName string
	MimeType string
	Size     int64
	// StorageKey is generated by the server and never exposed.
	StorageKey string
	// Checksum is the SHA-256 (hex) of the content. It changes only with the file, so a client can
	// tell a rename (new Version, same Checksum) from a new file.
	Checksum   string
	Status     Status
	Visibility Visibility
	// LinkType and LinkID optionally tie the document to another entity of the trip.
	LinkType string
	LinkID   string
}

func Base(d *Document) *kernel.Base { return &d.Base }

func (d Document) VisibleTo(actor user.ID) bool {
	return d.Visibility == VisibilityTrip || d.OwnerID == actor
}

type LinkInput struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}

func (v linkValidator) link(field string, in *LinkInput) (string, string) {
	if in == nil {
		return "", ""
	}
	v.Check(linkTypes[in.Type], field+".type", "must be one of trip, itinerary_item, flight, hotel, restaurant, place, transfer")
	v.Check(ids.IsValid(in.ID), field+".id", "must be a lowercase UUID")
	return in.Type, in.ID
}

type linkValidator struct{ *kernel.Validator }

// Storage is the port to the file store. The S3 adapter implements it; nothing in the domain
// knows about AWS.
type Storage interface {
	PresignUpload(ctx context.Context, key string, req UploadRequest) (Upload, error)
	// Stat reports the stored object, or ErrObjectNotFound.
	Stat(ctx context.Context, key string) (ObjectInfo, error)
	PresignDownload(ctx context.Context, key string, req DownloadRequest) (Upload, error)
	Delete(ctx context.Context, key string) error
}

var ErrObjectNotFound = errors.New("object not found")

const (
	UploadTTL   = 15 * time.Minute
	DownloadTTL = 5 * time.Minute
)

type UploadRequest struct {
	ContentType string
	Size        int64
	// ChecksumSHA256 is hex; the storage refuses an upload whose content does not match it.
	ChecksumSHA256 string
	TTL            time.Duration
}

type DownloadRequest struct {
	FileName    string
	ContentType string
	TTL         time.Duration
}

type ObjectInfo struct {
	Size           int64
	ContentType    string
	ChecksumSHA256 string
}

// Upload is a signed request the client performs against the storage.
type Upload struct {
	URL       string
	Method    string
	Headers   map[string]string
	ExpiresAt time.Time
}

// SanitizeFileName keeps only a safe base name: no directories, control characters or quotes.
func SanitizeFileName(name string) string {
	name = strings.ReplaceAll(name, "\\", "/")
	if i := strings.LastIndex(name, "/"); i >= 0 {
		name = name[i+1:]
	}
	var b strings.Builder
	for _, r := range name {
		if r < 0x20 || r == 0x7f || r == '"' {
			continue
		}
		b.WriteRune(r)
	}
	out := strings.TrimSpace(strings.TrimLeft(b.String(), "."))
	if len([]rune(out)) > 200 {
		out = string([]rune(out)[:200])
	}
	return out
}

// ContentDisposition forces a download and carries the file name for any client.
func ContentDisposition(fileName string) string {
	ascii := strings.Map(func(r rune) rune {
		if r > 0x7e || r < 0x20 || r == '"' || r == '\\' {
			return '_'
		}
		return r
	}, fileName)
	return `attachment; filename="` + ascii + `"; filename*=UTF-8''` + url.PathEscape(fileName)
}
